# Generated by Django 4.0.3 on 2022-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introverts', '0002_meals_strdrinkalternate'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='strArea',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='strCreativeCommonsConfirmed',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='strYoutube',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strImageSource',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strIngredient16',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strIngredient17',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strIngredient18',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strIngredient19',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strIngredient20',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strMeasure16',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strMeasure17',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strMeasure18',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strMeasure19',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='strMeasure20',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
