# Generated by Django 4.0.3 on 2022-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introverts', '0003_meals_strarea_meals_strcreativecommonsconfirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitems',
            name='strMealThumb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
