# Generated by Django 4.0.3 on 2022-05-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introverts', '0005_meals_datemodified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='strInstruction',
            new_name='strInstructions',
        ),
    ]
